[build]
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIzaSyBAZJ1VfbW4fUiZmKLrIJHoodqEelE8iIA"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions."email-semanal"]
  schedule = "0 12 * * 1"

[functions."email-mensual"]
  schedule = "0 12 1 * *"

[functions."bank-import"]
  timeout = 60

[functions."inflacion"]
  schedule = "0 10 20 * *"
